### ISSUE TITLE
🐛 Bug report: Custom error messages not displayed for number and text validation

### ISSUE THREAD

**Issue by iadereggalternova** [StanfordBDHG/ResearchKitOnFHIR#65]
### Description

I've noticed an issue where custom error messages for both Number and Text type questions in our survey forms aren't being displayed as expected. While the validations are functioning correctly, the custom error messages we've set up aren’t showing up when a user fails to meet the validation criteria.

### Reproduction

To give you a better idea, here’s how you can reproduce the issue:

### For Number Question
- Create a Number question with a validation rule limiting the number between 0 and 10.
- Include a custom error message in the FHIR Questionnaire for failed validations.
- In the application, enter a number outside the specified range.

### For Text Question
- Create a Text question with a regular expression validation for a maximum word count.
- Enter text exceeding the word limit.
- Notice the absence of the custom error message.

### JSON sample

```
{
  "title": "Test custom error message",
  "resourceType": "Questionnaire",
  "language": "en-US",
  "status": "draft",
  "publisher": "Stanford Biodesign Digital Health",
  "meta": {
    "profile": [
      "http://spezi.health/fhir/StructureDefinition/sdf-Questionnaire"
    ],
    "tag": [
      { "system": "urn:ietf:bcp:47", "code": "en-US", "display": "English" }
    ]
  },
  "useContext": [
    {
      "code": {
        "system": "http://hl7.org/fhir/ValueSet/usage-context-type",
        "code": "focus",
        "display": "Clinical Focus"
      },
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "urn:oid:2.16.578.1.12.4.1.1.8655",
            "display": "Test custom error message"
          }
        ]
      }
    }
  ],
  "contact": [{ "name": "http://spezi.health" }],
  "subjectType": ["Patient"],
  "url": "http://spezi.health/fhir/questionnaire/dd859ee0-4e7a-4131-f6fa-2239f0ad08b2",
  "item": [
    {
      "linkId": "282ca91c-5123-4c68-9755-8b5aab297dac",
      "type": "integer",
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/minValue",
          "valueInteger": 0
        },
        {
          "url": "http://hl7.org/fhir/StructureDefinition/maxValue",
          "valueInteger": 10
        },
        {
          "url": "http://ehelse.no/fhir/StructureDefinition/validationtext",
          "valueString": "Custom error message..."
        }
      ],
      "required": false,
      "text": "Please, rate your attention"
    },
    {
      "linkId": "1d0a234f-bbd2-4ef4-8b26-1110cce45efe",
      "type": "string",
      "text": "Please describe the characteristics of you pain?",
      "required": false,
      "extension": [
        {
          "url": "http://ehelse.no/fhir/StructureDefinition/validationtext",
          "valueString": "Custom error message..."
        },
        {
          "url": "http://hl7.org/fhir/StructureDefinition/regex",
          "valueString": "^\\s*\\S+(\\s+\\S+){0,2}\\s*$"
        }
      ]
    }
  ]
}
```

### Expected behavior

Ideally, when a user inputs data that doesn't meet the validation criteria, our custom error message should be displayed to guide them.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
Hi @iadereggalternova, the issue is that we use a different validation message extension in ResearchKitOnFHIR than you have in your JSON, which was likely generated with an older version of the Phoenix survey builder. If you update it to "http://biodesign.stanford.edu/fhir/StructureDefinition/validationtext", it should work with ResearchKitOnFHIR. Hope this helps!
