### ISSUE TITLE
🏎 Minor feature request: Questionnaire URL as an optional parameter

### ISSUE THREAD

**Issue by luppoalberto111** [StanfordBDHG/ResearchKitOnFHIR#75]
### Problem

According to FHIR [standard](https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.url) `URL` attribute has a cardinality between `0..1`.  Unfortunately, `ResearchKitOnFHIR` is strict in this case and doesn't accept questionnaires without `URL` even though the standard is still fulfilled.

Currently, this kind of restriction doesn't exist in equivalent libraries for Android and FE.

Also, there are currently 3rd party services that provide questionnaires without URL and are not presentable by this library.

### Solution

The best solution to this issue would be to make URL parameter of `ORKNavigableOrderedTask` optional.
In this case `FHIR URL` serves as an identifier of `ORKNavigableOrderedTask`.

Instead of throwing an error, we can put any non-url placeholder - static `String` or dynamic- for example `UUID`.

In the `public var fhirResponse: QuestionnaireResponse` we can put something like:

```
if let questionnaireURL = questionnaireID.flatMap(URL.init) {
    questionnaireResponse.questionnaire = FHIRPrimitive(Canonical(questionnaireURL))
}
```

### Additional context

Even though, this is a small improvement, it can be a dealbreaker for other people who use this library.
Of course, I can help with the implementation and currently, I'm not aware of any blocker. 

Small sidenote: I tried to inject URL to the `Questionnaire` but it causes crashes on Android in case you'd want to display responses from iOS on Android. You see, Android compares URL of `Questionnaire` vs `Responses`. And the discrepancy between these URLs is causing runtime crash on Android.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
@luppoalberto111 Feel free to create a PR to address this issue; using a reasonable default (e.g. title or a UUID string if non of them are there) sounds like a solid approach.

**Comment by vishnuravi** [comment]
Thank you for addressing the issue @luppoalberto111!
